from tkinter import *
import customtkinter
from tkinter import messagebox
from collections import Counter
#Collections module implements high-performance container datatypes (beyond the built-in types list, dict and tuple) 
#and contains many useful data structures that you can use to store information in memory
word_list = ['java','technology','beautiful','library']
score=0;
addedWord=[]
window=customtkinter.CTk()
window.title("PUZZLE-GAME")
window.geometry("1035x500")
def checkspells():
    global score
    word=(word_check.get()).lower()
    if word in word_list:
        if word.lower() in addedWord:
            messagebox.showinfo("Already Checked","You cannot enter one word twice!")
            return
        score=score+len(word)
        total="score = "+str(score)
        addedWord.append(word.lower())
        label.configure(text=total)
        if len(word_list)==len(addedWord):
            messagebox.showinfo("Wow!","You Guessed all the words great!!!")
            window.quit()
    else:
        messagebox.showinfo("Good try","No such word exists")
    word_check.delete(0, 'end')
def clear1():
    word_check.delete(0,'end')
    global score
    score=0
    global addedWord
    addedWord=[]
    total="score = "+str(score)
    label.configure(text=total)   
def InputHandler(arg):
    word=word_check.get()
    word_check.insert(len(word),arg)

# def enter(btn):
#     btn['bg'] = 'lightcyan3'
# def leave(btn):
#     btn['bg'] = 'white'

btn1 = customtkinter.CTkButton(window, text="A",width=86, command=lambda: InputHandler("A") )
btn1.grid(column=1, row=1)
# btn1.bind('<Enter>', lambda event, button=btn1: enter(button))
# btn1.bind('<Leave>', lambda event, button=btn1: leave(button))
btn2 = customtkinter.CTkButton(window, text="B",width=86, command=lambda: InputHandler("B") ) 
btn2.grid(column=2, row=1)
btn3 = customtkinter.CTkButton(window, text="C",width=86, command=lambda: InputHandler("C") )
btn3.grid(column=3, row=1)
btn4 = customtkinter.CTkButton(window, text="D",width=86, command=lambda: InputHandler("D") )
btn4.grid(column=4, row=1)
btn5 = customtkinter.CTkButton(window, text="W",width=86, command=lambda: InputHandler("W") )
btn5.grid(column=5, row=1)
btn6 = customtkinter.CTkButton(window, text="X",width=86, command=lambda: InputHandler("X") )
btn6.grid(column=6, row=1)
btn7 = customtkinter.CTkButton(window, text="K",width=86, command=lambda: InputHandler("K") )
btn7.grid(column=7, row=1)
btn8 = customtkinter.CTkButton(window, text="L",width=86, command=lambda: InputHandler("L") )
btn8.grid(column=8, row=1)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=1) 
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=1)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=1)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=1)
btn1 = customtkinter.CTkButton(window, text="X",width=86, command=lambda: InputHandler("X") )
btn1.grid(column=1, row=2)
btn2 = customtkinter.CTkButton(window, text="E",width=86, command=lambda: InputHandler("E") )
btn2.grid(column=2, row=2)
btn3 = customtkinter.CTkButton(window, text="I",width=86, command=lambda: InputHandler("I") )
btn3.grid(column=3, row=2)
btn4 = customtkinter.CTkButton(window, text="J",width=86, command=lambda: InputHandler("J") )
btn4.grid(column=4, row=2) 
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=2)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=2)
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=2)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=2)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=2)
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=2)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=2)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=2)

btn1 = customtkinter.CTkButton(window, text="M",width=86, command=lambda: InputHandler("M") )
btn1.grid(column=1, row=3)
btn2 = customtkinter.CTkButton(window, text="A",width=86, command=lambda: InputHandler("A") )
btn2.grid(column=2, row=3)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=3)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=3)
btn5 = customtkinter.CTkButton(window, text="A",width=86, command=lambda: InputHandler("A") )
btn5.grid(column=5, row=3)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=3)
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=3)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=3)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=3)
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=3)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=3)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=3)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=4)
btn2 = customtkinter.CTkButton(window, text="U",width=86, command=lambda: InputHandler("U") )
btn2.grid(column=2, row=4)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=4)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=4)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=4)
btn6 = customtkinter.CTkButton(window, text="V",width=86, command=lambda: InputHandler("V") )
btn6.grid(column=6, row=4)
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=4)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=4)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=4)
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=4)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=4)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=4)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=5)
btn2 = customtkinter.CTkButton(window, text="T",width=86, command=lambda: InputHandler("T") )
btn2.grid(column=2, row=5)
btn3 = customtkinter.CTkButton(window, text="E",width=86, command=lambda: InputHandler("E") )
btn3.grid(column=3, row=5)
btn4 = customtkinter.CTkButton(window, text="C",width=86, command=lambda: InputHandler("C") )
btn4.grid(column=4, row=5)
btn5 = customtkinter.CTkButton(window, text="H",width=86, command=lambda: InputHandler("H") )
btn5.grid(column=5, row=5)
btn6 = customtkinter.CTkButton(window, text="N",width=86, command=lambda: InputHandler("N") )
btn6.grid(column=6, row=5)
btn7 = customtkinter.CTkButton(window, text="O",width=86, command=lambda: InputHandler("O") )
btn7.grid(column=7, row=5)
btn8 = customtkinter.CTkButton(window, text="L",width=86, command=lambda: InputHandler("L") )
btn8.grid(column=8, row=5)
btn9 = customtkinter.CTkButton(window, text="O",width=86, command=lambda: InputHandler("O") )
btn9.grid(column=9, row=5)
btn10 = customtkinter.CTkButton(window, text="G",width=86, command=lambda: InputHandler("G") )
btn10.grid(column=10, row=5)
btn11 = customtkinter.CTkButton(window, text="Y",width=86, command=lambda: InputHandler("Y") )
btn11.grid(column=11, row=5)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=5)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=6)
btn2 = customtkinter.CTkButton(window, text="I",width=86, command=lambda: InputHandler("I") )
btn2.grid(column=2, row=6)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=6)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=6)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=6)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=6)
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=6)
btn8 = customtkinter.CTkButton(window, text="J",width=86, command=lambda: InputHandler("J") )
btn8.grid(column=8, row=6)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=6)
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=6)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=6)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=6)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=7)
btn2 = customtkinter.CTkButton(window, text="F",width=86, command=lambda: InputHandler("F") )
btn2.grid(column=2, row=7)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=7) 
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=7)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=7)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=7)
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=7)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=7)
btn9 = customtkinter.CTkButton(window, text="A",width=86, command=lambda: InputHandler("A") )
btn9.grid(column=9, row=7)
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=7)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") ) 
btn11.grid(column=11, row=7)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=7)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=8)
btn2 = customtkinter.CTkButton(window, text="U",width=86, command=lambda: InputHandler("U") )
btn2.grid(column=2, row=8)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=8)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=8)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=8)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=8) 
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=8)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=8)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=8)
btn10 = customtkinter.CTkButton(window, text="V",width=86, command=lambda: InputHandler("V") )
btn10.grid(column=10, row=8)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=8)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=8)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=9) 
btn2 = customtkinter.CTkButton(window, text="L",width=86, command=lambda: InputHandler("L") )
btn2.grid(column=2, row=9)
btn3 = customtkinter.CTkButton(window, text="I",width=86, command=lambda: InputHandler("I") )
btn3.grid(column=3, row=9)
btn4 = customtkinter.CTkButton(window, text="B",width=86, command=lambda: InputHandler("B") )
btn4.grid(column=4, row=9)
btn5 = customtkinter.CTkButton(window, text="R",width=86, command=lambda: InputHandler("R") )
btn5.grid(column=5, row=9)
btn6 = customtkinter.CTkButton(window, text="A",width=86, command=lambda: InputHandler("A") )
btn6.grid(column=6, row=9)
btn7 = customtkinter.CTkButton(window, text="R",width=86, command=lambda: InputHandler("R") )
btn7.grid(column=7, row=9)
btn8 = customtkinter.CTkButton(window, text="Y",width=86, command=lambda: InputHandler("Y") )
btn8.grid(column=8, row=9)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") ) 
btn9.grid(column=9, row=9)
btn10 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn10.grid(column=10, row=9)
btn11 = customtkinter.CTkButton(window, text="A",width=86, command=lambda: InputHandler("A") )
btn11.grid(column=11, row=9)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=9)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=10)
btn2 = customtkinter.CTkButton(window, text="",width=86, command=lambda: InputHandler("") )
btn2.grid(column=2, row=10)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=10)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=10)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=10)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=10) 
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=10)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=10)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=10)
btn10 = customtkinter.CTkButton(window, text="",width=86, command=lambda: InputHandler("") )
btn10.grid(column=10, row=10)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=10)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=10)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=11)
btn2 = customtkinter.CTkButton(window, text="",width=86, command=lambda: InputHandler("") )
btn2.grid(column=2, row=11)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=11)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=11)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=11)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=11) 
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=11)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=11)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=11)
btn10 = customtkinter.CTkButton(window, text="",width=86, command=lambda: InputHandler("") )
btn10.grid(column=10, row=11)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=11)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=11)

btn1 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn1.grid(column=1, row=12)
btn2 = customtkinter.CTkButton(window, text="",width=86, command=lambda: InputHandler("") )
btn2.grid(column=2, row=12)
btn3 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn3.grid(column=3, row=12)
btn4 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn4.grid(column=4, row=12)
btn5 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn5.grid(column=5, row=12)
btn6 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn6.grid(column=6, row=12) 
btn7 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn7.grid(column=7, row=12)
btn8 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn8.grid(column=8, row=12)
btn9 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn9.grid(column=9, row=12)
btn10 = customtkinter.CTkButton(window, text="",width=86, command=lambda: InputHandler("") )
btn10.grid(column=10, row=12)
btn11 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn11.grid(column=11, row=12)
btn12 = customtkinter.CTkButton(window, text="", width=86,command=lambda: InputHandler("") )
btn12.grid(column=12, row=12)

word_check=customtkinter.CTkEntry(window,text_font=('','27'))
word_check.place(height=50,width=470)
word_check.place(x=300,y=350)
word_check.focus()
btncheck = customtkinter.CTkButton(window, text="OK",height=32,command=checkspells)
btncheck.place(x = 300, y = 400)
btncheck = customtkinter.CTkButton(window, text="RESET",height=32,command=clear1)
btncheck.place(x = 540, y = 400)
label=customtkinter.CTkLabel(window,text=" Score = 0",bg="TUrquoise", fg="black",width=9,text_font=('','40'))
label.place(x=350, y=440)
window.mainloop()